name: pp_8
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  firebase_remote_config: ^4.3.8
  http: ^1.1.2
  hive: ^2.2.3
  flutter_gen: ^5.3.2
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  image_network: ^2.5.4+1
  path_provider: ^2.1.1
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/exchanges/

